version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Mount the schema script
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
